loading dictionary from /home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/data/dictionary_tdiuc.pkl
Namespace(buffer_replacement_strategy='random', config_name='TDIUC_streaming', data_order='iid', expt_name='TDIUC_streaming_iid_2e-3', full=False, lr=0.002, max_buffer_size=None, rehearsal_mode=None, resume_from=None, stream=False, stream_with_rehearsal=True, use_exponential_averaging=False)
Building Dataloaders
Traceback (most recent call last):
  File "vqa_trainer.py", line 487, in <module>
    main()
  File "vqa_trainer.py", line 433, in main
    if not args.only_qtype:
AttributeError: 'Namespace' object has no attribute 'only_qtype'
loading dictionary from /home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/data/dictionary_tdiuc.pkl
usage: vqa_trainer.py [-h] --config_name CONFIG_NAME --expt_name EXPT_NAME
                      [--full] [--stream] [--data_order {iid,qtype}]
                      [--stream_with_rehearsal]
                      [--rehearsal_mode {default,limited_buffer}]
                      [--max_buffer_size MAX_BUFFER_SIZE]
                      [--buffer_replacement_strategy {queue,random}] [--lr LR]
                      [--use_exponential_averaging]
vqa_trainer.py: error: unrecognized arguments: --only_qtype False
loading dictionary from /home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/data/dictionary_tdiuc.pkl
usage: vqa_trainer.py [-h] --config_name CONFIG_NAME --expt_name EXPT_NAME
                      [--full] [--stream] [--data_order {iid,qtype}]
                      [--stream_with_rehearsal]
                      [--rehearsal_mode {default,limited_buffer}]
                      [--max_buffer_size MAX_BUFFER_SIZE]
                      [--buffer_replacement_strategy {queue,random}] [--lr LR]
                      [--only_qtype ONLY_QTYPE] [--use_exponential_averaging]
vqa_trainer.py: error: argument --only_qtype: expected one argument
loading dictionary from /home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/data/dictionary_tdiuc.pkl
Namespace(buffer_replacement_strategy='random', config_name='TDIUC_streaming', data_order='iid', expt_name='TDIUC_streaming_iid_2e-3', full=False, lr=0.002, max_buffer_size=None, only_qtype=-1, rehearsal_mode=None, resume_from=None, stream=False, stream_with_rehearsal=True, use_exponential_averaging=False)
Building Dataloaders
Loading Train Data
Filtering Train Data
Loading Test Data
Filtering Test Data
UpDown(
  (ques_encoder): QuestionEncoder(
    (embedding): WordEmbedding(
      (emb): Embedding(9319, 300)
      (dropout): Dropout(p=0.5, inplace=False)
    )
    (lstm): LSTM(300, 512, bidirectional=True)
  )
  (attention): ModuleList(
    (0): Attention(
      (nlin): Linear(in_features=3072, out_features=1024, bias=True)
      (attnmap): Linear(in_features=1024, out_features=1, bias=True)
      (relu): ReLU()
      (dropout): Dropout(p=0.5, inplace=False)
    )
    (1): Attention(
      (nlin): Linear(in_features=3072, out_features=1024, bias=True)
      (attnmap): Linear(in_features=1024, out_features=1, bias=True)
      (relu): ReLU()
      (dropout): Dropout(p=0.5, inplace=False)
    )
  )
  (classifier): Classifier(
    (relu): ReLU(inplace=True)
    (lin1): Linear(in_features=5120, out_features=2048, bias=True)
    (classifier): Linear(in_features=2048, out_features=1480, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
)
Training...
Using lr specified in args 0.002
{
    "buffer_replacement_strategy": "random",
    "config_name": "TDIUC_streaming",
    "data_order": "iid",
    "expt_name": "TDIUC_streaming_iid_2e-3",
    "full": false,
    "lr": 0.002,
    "max_buffer_size": null,
    "only_qtype": -1,
    "rehearsal_mode": null,
    "resume_from": null,
    "stream": false,
    "stream_with_rehearsal": true,
    "use_exponential_averaging": false
}

Performing base init on 5000 data points
Traceback (most recent call last):
  File "vqa_trainer.py", line 486, in <module>
    main()
  File "vqa_trainer.py", line 481, in main
    train_base_init(config, net, train_data, val_data, optimizer, criterion, args.expt_name, net_running)
  File "vqa_trainer.py", line 127, in train_base_init
    training_loop(config, net, base_init_data_loader, val_data, optimizer, criterion, expt_name, net_running)
  File "vqa_trainer.py", line 100, in training_loop
    acc, vqa_acc = train_epoch(net, criterion, optimizer, train_data, epoch, net_running)
  File "vqa_trainer.py", line 148, in train_epoch
    for qfeat, qseq, imfeat, qid, iid, aidx, ten_aidx, qlen in data:
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/vqa_dataloader.py", line 154, in __getitem__
    return self.get_datapoint(index)
  File "/home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/vqa_dataloader.py", line 166, in get_datapoint
    imfeat = self.feat['image_features'][feat_index]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 451, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 471, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (26904) out of range (0-11462)

loading dictionary from /home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/data/dictionary_tdiuc.pkl
Namespace(buffer_replacement_strategy='random', config_name='TDIUC_streaming', data_order='iid', expt_name='TDIUC_streaming_iid_2e-3', full=False, lr=0.002, max_buffer_size=None, only_qtype=-1, rehearsal_mode=None, resume_from=None, stream=False, stream_with_rehearsal=True, use_exponential_averaging=False)
Building Dataloaders
Loading Train Data
Filtering Train Data
Loading Test Data
Filtering Test Data
UpDown(
  (ques_encoder): QuestionEncoder(
    (embedding): WordEmbedding(
      (emb): Embedding(9319, 300)
      (dropout): Dropout(p=0.5, inplace=False)
    )
    (lstm): LSTM(300, 512, bidirectional=True)
  )
  (attention): ModuleList(
    (0): Attention(
      (nlin): Linear(in_features=3072, out_features=1024, bias=True)
      (attnmap): Linear(in_features=1024, out_features=1, bias=True)
      (relu): ReLU()
      (dropout): Dropout(p=0.5, inplace=False)
    )
    (1): Attention(
      (nlin): Linear(in_features=3072, out_features=1024, bias=True)
      (attnmap): Linear(in_features=1024, out_features=1, bias=True)
      (relu): ReLU()
      (dropout): Dropout(p=0.5, inplace=False)
    )
  )
  (classifier): Classifier(
    (relu): ReLU(inplace=True)
    (lin1): Linear(in_features=5120, out_features=2048, bias=True)
    (classifier): Linear(in_features=2048, out_features=1480, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
)
Training...
Using lr specified in args 0.002
{
    "buffer_replacement_strategy": "random",
    "config_name": "TDIUC_streaming",
    "data_order": "iid",
    "expt_name": "TDIUC_streaming_iid_2e-3",
    "full": false,
    "lr": 0.002,
    "max_buffer_size": null,
    "only_qtype": -1,
    "rehearsal_mode": null,
    "resume_from": null,
    "stream": false,
    "stream_with_rehearsal": true,
    "use_exponential_averaging": false
}

Performing base init on 5000 data points
Traceback (most recent call last):
  File "vqa_trainer.py", line 486, in <module>
    main()
  File "vqa_trainer.py", line 481, in main
    train_base_init(config, net, train_data, val_data, optimizer, criterion, args.expt_name, net_running)
  File "vqa_trainer.py", line 127, in train_base_init
    training_loop(config, net, base_init_data_loader, val_data, optimizer, criterion, expt_name, net_running)
  File "vqa_trainer.py", line 100, in training_loop
    acc, vqa_acc = train_epoch(net, criterion, optimizer, train_data, epoch, net_running)
  File "vqa_trainer.py", line 148, in train_epoch
    for qfeat, qseq, imfeat, qid, iid, aidx, ten_aidx, qlen in data:
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/vqa_dataloader.py", line 154, in __getitem__
    return self.get_datapoint(index)
  File "/home/qzhb/dorren/CL4VQA/REMIND/VQA_Experiment/vqa_dataloader.py", line 166, in get_datapoint
    imfeat = self.feat['image_features'][feat_index]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 451, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/qzhb/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 471, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (20217) out of range (0-11462)

